# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 625)
        MainWindow.setMinimumSize(QtCore.QSize(750, 625))
        MainWindow.setMaximumSize(QtCore.QSize(750, 625))
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(206, 208, 212);\n"
"border: 4px solid black")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(206, 208, 212);")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 10, 721, 561))
        self.stackedWidget.setStyleSheet("border: none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.menu = QtWidgets.QWidget()
        self.menu.setObjectName("menu")
        self.bttnPorcentaje = QtWidgets.QPushButton(self.menu)
        self.bttnPorcentaje.setGeometry(QtCore.QRect(230, 350, 261, 71))
        self.bttnPorcentaje.setAutoFillBackground(False)
        self.bttnPorcentaje.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.bttnPorcentaje.setObjectName("bttnPorcentaje")
        self.bttnCalculadora = QtWidgets.QPushButton(self.menu)
        self.bttnCalculadora.setGeometry(QtCore.QRect(230, 190, 261, 71))
        self.bttnCalculadora.setAutoFillBackground(False)
        self.bttnCalculadora.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.bttnCalculadora.setObjectName("bttnCalculadora")
        self.bttnImc = QtWidgets.QPushButton(self.menu)
        self.bttnImc.setGeometry(QtCore.QRect(230, 270, 261, 71))
        self.bttnImc.setAutoFillBackground(False)
        self.bttnImc.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.bttnImc.setObjectName("bttnImc")
        self.gridLayoutWidget = QtWidgets.QWidget(self.menu)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 60, 301, 91))
        self.gridLayoutWidget.setAutoFillBackground(False)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.menuTitle = QtWidgets.QLabel(self.gridLayoutWidget)
        self.menuTitle.setAutoFillBackground(False)
        self.menuTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 150, 255);\n"
"font-weight: bold;")
        self.menuTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.menuTitle.setObjectName("menuTitle")
        self.gridLayout.addWidget(self.menuTitle, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.menu)
        self.calculadora = QtWidgets.QWidget()
        self.calculadora.setObjectName("calculadora")
        self.widget = QtWidgets.QWidget(self.calculadora)
        self.widget.setGeometry(QtCore.QRect(90, 20, 481, 481))
        self.widget.setStyleSheet("border: 4px solid black;\n"
"font: 75 10pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.Pantalla = QtWidgets.QLabel(self.widget)
        self.Pantalla.setGeometry(QtCore.QRect(0, 0, 481, 101))
        self.Pantalla.setObjectName("Pantalla")
        self.Pantalla.setStyleSheet("font: 75 16pt \"Verdana\";\n")
        self.Pantalla.setAlignment(QtCore.Qt.AlignCenter)
        self.pushButton_pot = QtWidgets.QPushButton(self.widget)
        self.pushButton_pot.setGeometry(QtCore.QRect(0, 130, 121, 71))
        self.pushButton_pot.setObjectName("pushButton_pot")
        self.pushButton_ce = QtWidgets.QPushButton(self.widget)
        self.pushButton_ce.setGeometry(QtCore.QRect(120, 130, 121, 71))
        self.pushButton_ce.setObjectName("pushButton_ce")
        self.pushButton_c = QtWidgets.QPushButton(self.widget)
        self.pushButton_c.setGeometry(QtCore.QRect(240, 130, 121, 71))
        self.pushButton_c.setObjectName("pushButton_c")
        self.pushButton_dividir = QtWidgets.QPushButton(self.widget)
        self.pushButton_dividir.setGeometry(QtCore.QRect(360, 130, 121, 71))
        self.pushButton_dividir.setObjectName("pushButton_dividir")
        self.pushButton_nueve = QtWidgets.QPushButton(self.widget)
        self.pushButton_nueve.setGeometry(QtCore.QRect(240, 200, 121, 71))
        self.pushButton_nueve.setObjectName("pushButton_nueve")
        self.pushButton_siete = QtWidgets.QPushButton(self.widget)
        self.pushButton_siete.setGeometry(QtCore.QRect(0, 200, 121, 71))
        self.pushButton_siete.setObjectName("pushButton_siete")
        self.pushButton_ocho = QtWidgets.QPushButton(self.widget)
        self.pushButton_ocho.setGeometry(QtCore.QRect(120, 200, 121, 71))
        self.pushButton_ocho.setObjectName("pushButton_ocho")
        self.pushButton_multi = QtWidgets.QPushButton(self.widget)
        self.pushButton_multi.setGeometry(QtCore.QRect(360, 200, 121, 71))
        self.pushButton_multi.setObjectName("pushButton_multi")
        self.pushButton_seis = QtWidgets.QPushButton(self.widget)
        self.pushButton_seis.setGeometry(QtCore.QRect(240, 270, 121, 71))
        self.pushButton_seis.setObjectName("pushButton_seis")
        self.pushButton_cuatro = QtWidgets.QPushButton(self.widget)
        self.pushButton_cuatro.setGeometry(QtCore.QRect(0, 270, 121, 71))
        self.pushButton_cuatro.setObjectName("pushButton_cuatro")
        self.pushButton_cinco = QtWidgets.QPushButton(self.widget)
        self.pushButton_cinco.setGeometry(QtCore.QRect(120, 270, 121, 71))
        self.pushButton_cinco.setObjectName("pushButton_cinco")
        self.pushButton_resta = QtWidgets.QPushButton(self.widget)
        self.pushButton_resta.setGeometry(QtCore.QRect(360, 270, 121, 71))
        self.pushButton_resta.setObjectName("pushButton_resta")
        self.pushButton_tres = QtWidgets.QPushButton(self.widget)
        self.pushButton_tres.setGeometry(QtCore.QRect(240, 340, 121, 71))
        self.pushButton_tres.setObjectName("pushButton_tres")
        self.pushButton_uno = QtWidgets.QPushButton(self.widget)
        self.pushButton_uno.setGeometry(QtCore.QRect(0, 340, 121, 71))
        self.pushButton_uno.setObjectName("pushButton_uno")
        self.pushButton_dos = QtWidgets.QPushButton(self.widget)
        self.pushButton_dos.setGeometry(QtCore.QRect(120, 340, 121, 71))
        self.pushButton_dos.setObjectName("pushButton_dos")
        self.pushButton_suma = QtWidgets.QPushButton(self.widget)
        self.pushButton_suma.setGeometry(QtCore.QRect(360, 340, 121, 71))
        self.pushButton_suma.setObjectName("pushButton_suma")
        self.pushButton_igual = QtWidgets.QPushButton(self.widget)
        self.pushButton_igual.setGeometry(QtCore.QRect(240, 410, 241, 71))
        self.pushButton_igual.setObjectName("pushButton_igual")
        self.pushButton_cero = QtWidgets.QPushButton(self.widget)
        self.pushButton_cero.setGeometry(QtCore.QRect(0, 410, 121, 71))
        self.pushButton_cero.setObjectName("pushButton_cero")
        self.pushButton_decimal = QtWidgets.QPushButton(self.widget)
        self.pushButton_decimal.setGeometry(QtCore.QRect(120, 410, 121, 71))
        self.pushButton_decimal.setObjectName("pushButton_decimal")
        self.menubttn = QtWidgets.QPushButton(self.calculadora)
        self.menubttn.setGeometry(QtCore.QRect(580, 520, 111, 31))
        self.menubttn.setStyleSheet("background-color: rgb(86, 73, 149);\n"
"border: 2px solid black;\n"
"font-weight: bold;")
        self.menubttn.setObjectName("menubttn")
        self.stackedWidget.addWidget(self.calculadora)
        self.calc_imc = QtWidgets.QWidget()
        self.calc_imc.setObjectName("calc_imc")
        self.label_3 = QtWidgets.QLabel(self.calc_imc)
        self.label_3.setGeometry(QtCore.QRect(370, 190, 301, 221))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imc.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.calc_imc)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 230, 104, 31))
        self.textEdit_2.setStyleSheet("\n"
"border:0px;\n"
"background-color: rgb(206, 208, 212);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_Calc = QtWidgets.QPushButton(self.calc_imc)
        self.pushButton_Calc.setGeometry(QtCore.QRect(160, 300, 81, 31))
        self.pushButton_Calc.setStyleSheet("border:2px solid black;\n"
"background-color: rgb(86, 73, 149);")
        self.pushButton_Calc.setObjectName("pushButton_Calc")
        self.textEdit_3 = QtWidgets.QTextEdit(self.calc_imc)
        self.textEdit_3.setGeometry(QtCore.QRect(60, 370, 104, 31))
        self.textEdit_3.setStyleSheet("\n"
"border:0px;\n"
"background-color: rgb(206, 208, 212);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_Borrar = QtWidgets.QPushButton(self.calc_imc)
        self.pushButton_Borrar.setGeometry(QtCore.QRect(250, 300, 81, 31))
        self.pushButton_Borrar.setStyleSheet("border:2px solid black;\n"
"background-color: rgb(86, 73, 149);")
        self.pushButton_Borrar.setObjectName("pushButton_Borrar")
        self.menuTitle_2 = QtWidgets.QLabel(self.calc_imc)
        self.menuTitle_2.setGeometry(QtCore.QRect(180, 50, 301, 81))
        self.menuTitle_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 150, 255);\n"
"border:2px solid black;\n"
"font-weight: bold;")
        self.menuTitle_2.setObjectName("menuTitle_2")
        self.cPeso = QtWidgets.QLineEdit(self.calc_imc)
        self.cPeso.setGeometry(QtCore.QRect(160, 190, 171, 31))
        self.cPeso.setStyleSheet("border:2px solid black;")
        self.cPeso.setObjectName("cPeso")
        self.textEdit = QtWidgets.QTextEdit(self.calc_imc)
        self.textEdit.setGeometry(QtCore.QRect(50, 190, 104, 31))
        self.textEdit.setStyleSheet("\n"
"border:0px;\n"
"background-color: rgb(206, 208, 212);")
        self.textEdit.setObjectName("textEdit")
        self.cAltura = QtWidgets.QLineEdit(self.calc_imc)
        self.cAltura.setGeometry(QtCore.QRect(160, 230, 171, 31))
        self.cAltura.setStyleSheet("border:2px solid black;")
        self.cAltura.setObjectName("cAltura")
        self.menubttn_2 = QtWidgets.QPushButton(self.calc_imc)
        self.menubttn_2.setGeometry(QtCore.QRect(560, 500, 111, 31))
        self.menubttn_2.setStyleSheet("background-color: rgb(86, 73, 149);\n"
"border: 2px solid black;\n"
"font-weight: bold;")
        self.menubttn_2.setObjectName("menubttn_2")
        self.cResultado = QtWidgets.QLabel(self.calc_imc)
        self.cResultado.setGeometry(QtCore.QRect(160, 400, 171, 101))
        self.cResultado.setStyleSheet("border:2px solid black;")
        self.cResultado.setText("")
        self.cResultado.setObjectName("cResultado")
        self.stackedWidget.addWidget(self.calc_imc)
        self.calc_porc = QtWidgets.QWidget()
        self.calc_porc.setObjectName("calc_porc")
        self.cPorc = QtWidgets.QLineEdit(self.calc_porc)
        self.cPorc.setGeometry(QtCore.QRect(290, 230, 181, 31))
        self.cPorc.setStyleSheet("border:2px solid black;")
        self.cPorc.setObjectName("cPorc")
        self.textEdit_4 = QtWidgets.QTextEdit(self.calc_porc)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 180, 261, 31))
        self.textEdit_4.setStyleSheet("\n"
"border:0px;\n"
"background-color: rgb(206, 208, 212);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.calc_porc)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 230, 261, 31))
        self.textEdit_5.setStyleSheet("\n"
"border:0px;\n"
"background-color: rgb(206, 208, 212);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.calc_porc)
        self.textEdit_6.setGeometry(QtCore.QRect(150, 350, 131, 31))
        self.textEdit_6.setStyleSheet("\n"
"border:0px;\n"
"background-color: rgb(206, 208, 212);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.menuTitle_3 = QtWidgets.QLabel(self.calc_porc)
        self.menuTitle_3.setGeometry(QtCore.QRect(220, 60, 301, 81))
        self.menuTitle_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(51, 150, 255);\n"
"border:2px solid black;\n"
"font-weight: bold;")
        self.menuTitle_3.setObjectName("menuTitle_3")
        self.cNumero = QtWidgets.QLineEdit(self.calc_porc)
        self.cNumero.setGeometry(QtCore.QRect(290, 180, 181, 31))
        self.cNumero.setStyleSheet("border:2px solid black;")
        self.cNumero.setObjectName("cNumero")
        self.pushButton_calcP = QtWidgets.QPushButton(self.calc_porc)
        self.pushButton_calcP.setGeometry(QtCore.QRect(290, 280, 81, 31))
        self.pushButton_calcP.setStyleSheet("border:2px solid black;\n"
"background-color: rgb(86, 73, 149);\n"
"font-weight: bold;")
        self.pushButton_calcP.setObjectName("pushButton_calcP")
        self.pushButton_borrarP = QtWidgets.QPushButton(self.calc_porc)
        self.pushButton_borrarP.setGeometry(QtCore.QRect(390, 280, 81, 31))
        self.pushButton_borrarP.setStyleSheet("border:2px solid black;\n"
"background-color: rgb(86, 73, 149);\n"
"font-weight: bold;")
        self.pushButton_borrarP.setObjectName("pushButton_borrarP")
        self.menubttn_3 = QtWidgets.QPushButton(self.calc_porc)
        self.menubttn_3.setGeometry(QtCore.QRect(590, 510, 111, 31))
        self.menubttn_3.setStyleSheet("background-color: rgb(86, 73, 149);\n"
"border: 2px solid black;\n"
"font-weight: bold;")
        self.menubttn_3.setObjectName("menubttn_3")
        self.cResultadoP = QtWidgets.QLineEdit(self.calc_porc)
        self.cResultadoP.setGeometry(QtCore.QRect(290, 350, 181, 31))
        self.cResultadoP.setStyleSheet("border:2px solid black;")
        self.cResultadoP.setReadOnly(True)
        self.cResultadoP.setObjectName("cResultadoP")
        self.stackedWidget.addWidget(self.calc_porc)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 750, 29))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actionkyjyhj = QtWidgets.QAction(MainWindow)
        self.actionkyjyhj.setObjectName("actionkyjyhj")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.activar_botones()
        # Botones calculadora imc
        self.pushButton_Calc.clicked.connect(self.calcular_imc)
        self.pushButton_Borrar.clicked.connect(self.borrar_imc)
        # Botones calculadora porcentajes
        self.pushButton_calcP.clicked.connect(self.calcular_porcentaje)
        self.pushButton_borrarP.clicked.connect(self.borrar_porcentaje)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bttnPorcentaje.setText(_translate("MainWindow", "Calculadora de porcentajes"))
        self.bttnCalculadora.setToolTip(_translate("MainWindow", "<html><head/><body><p>Calculadora</p></body></html>"))
        self.bttnCalculadora.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bttnCalculadora.setText(_translate("MainWindow", "Calculadora"))
        self.bttnImc.setText(_translate("MainWindow", "Calculadora de IMC"))
        self.menuTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Seleccione su tipo </span></p><p align=\"center\"><span style=\" font-size:16pt;\">de calculadora</span></p></body></html>"))
        #self.Pantalla.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_pot.setText(_translate("MainWindow", "x^2"))
        self.pushButton_ce.setText(_translate("MainWindow", "CE"))
        self.pushButton_c.setText(_translate("MainWindow", "C"))
        self.pushButton_dividir.setText(_translate("MainWindow", "/"))
        self.pushButton_nueve.setText(_translate("MainWindow", "9"))
        self.pushButton_siete.setText(_translate("MainWindow", "7"))
        self.pushButton_ocho.setText(_translate("MainWindow", "8"))
        self.pushButton_multi.setText(_translate("MainWindow", "*"))
        self.pushButton_seis.setText(_translate("MainWindow", "6"))
        self.pushButton_cuatro.setText(_translate("MainWindow", "4"))
        self.pushButton_cinco.setText(_translate("MainWindow", "5"))
        self.pushButton_resta.setText(_translate("MainWindow", "-"))
        self.pushButton_tres.setText(_translate("MainWindow", "3"))
        self.pushButton_uno.setText(_translate("MainWindow", "1"))
        self.pushButton_dos.setText(_translate("MainWindow", "2"))
        self.pushButton_suma.setText(_translate("MainWindow", "+"))
        self.pushButton_igual.setText(_translate("MainWindow", "="))
        self.pushButton_cero.setText(_translate("MainWindow", "0"))
        self.pushButton_decimal.setText(_translate("MainWindow", ","))
        self.menubttn.setText(_translate("MainWindow", "Volver al menú"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Altura</span></p></body></html>"))
        self.pushButton_Calc.setText(_translate("MainWindow", "Calcular"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Resultado</span></p></body></html>"))
        self.pushButton_Borrar.setText(_translate("MainWindow", "Borrar"))
        self.menuTitle_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Calculadora de IMC</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Peso</span></p></body></html>"))
        self.menubttn_2.setText(_translate("MainWindow", "Volver al menú"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Introduce el número:</span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Introduce el procentaje:</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Resultado:</span></p></body></html>"))
        self.menuTitle_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Calculadora de porcentajes</span></p></body></html>"))
        self.pushButton_calcP.setText(_translate("MainWindow", "Calcular"))
        self.pushButton_borrarP.setText(_translate("MainWindow", "Borrar"))
        self.menubttn_3.setText(_translate("MainWindow", "Volver al menú"))
        self.actionkyjyhj.setText(_translate("MainWindow", "kyjyhj"))
        
    def activar_botones(self):
        self.pushButton_cero.clicked.connect(self.cero)
        
        self.pushButton_uno.clicked.connect(self.uno)
        self.pushButton_dos.clicked.connect(self.dos)
        self.pushButton_tres.clicked.connect(self.tres)
        self.pushButton_cuatro.clicked.connect(self.cuatro)
        self.pushButton_cinco.clicked.connect(self.cinco)
        self.pushButton_seis.clicked.connect(self.seis)
        self.pushButton_siete.clicked.connect(self.siete)
        self.pushButton_ocho.clicked.connect(self.ocho)
        self.pushButton_nueve.clicked.connect(self.nueve)
        self.pushButton_decimal.clicked.connect(self.coma)
        self.pushButton_suma.clicked.connect(self.sumar)
        self.pushButton_resta.clicked.connect(self.restar)
        self.pushButton_multi.clicked.connect(self.multi)
        self.pushButton_dividir.clicked.connect(self.dividir)
        self.pushButton_c.clicked.connect(self.limpiar_c)
        self.pushButton_ce.clicked.connect(self.limpiar_ce)
        self.pushButton_pot.clicked.connect(self.potencia)
        self.pushButton_igual.clicked.connect(self.igual)
    
    def uno(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"1") 

    def dos(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"2") 

    def tres(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"3") 

    def cuatro(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"4") 

    def cinco(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"5") 

    def seis(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"6") 

    def siete(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"7") 

    def ocho(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"8") 

    def nueve(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"9")

    def cero(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+"0")

    def coma(self):
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+",")  
        
    def guardar_cosas(self):
        primero_numero = int(cadena)
        segundo_numero = int(cadena)
 
    def sumar(self): 
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+" + ")  
    
    def restar(self): 
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+" - ")
        
    def multi(self): 
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+" * ") 
        
    def dividir(self): 
        cadena=self.Pantalla.text()
        self.Pantalla.setText(cadena+" / ")         
    
    def limpiar_c(self): 
        self.Pantalla.setText("") 
  
    def limpiar_ce(self): 
        cadena = self.Pantalla.text() 
        self.Pantalla.setText(cadena[:len(cadena)-1]) 
        
    def igual(self): 
        texto = self.Pantalla.text() 
        print(texto)
        try:            
            ans = eval(texto) 
            self.Pantalla.setText(str(ans)) 
        
        except: 
            self.Pantalla.setText("Wrong Input") 
  
    def potencia(self):
        cadena = float(self.Pantalla.text())
        potencia = pow(cadena, 2)
        self.Pantalla.setText(str(potencia)) 
        
    def calcular_imc(self):
        peso = float(self.cPeso.text())
        altura = float(self.cAltura.text())
        imc = peso / (altura * altura)
        
        if ( imc <= 18.5):
            self.cResultado.setText("Peso inferior al normal.\nTu IMC es "+ str('%.2f' % imc))
        elif ( imc <= 24.9):
           self.cResultado.setText("Peso Normal.\nTu IMC es "+ str('%.2f' % imc))

        elif ( imc <= 29.9):
            self.cResultado.setText("Sobrepeso.\nTu IMC es " + str('%.2f' % imc))
            
        elif ( imc >= 30):
            self.cResultado.setText("Obeso.\nTu IMC es " + str('%.2f' % imc))

        elif ( imc >= 35):
            self.cResultado.setText("Obeso Mórbido.\nTu IMC es " + str('%.2f' % imc))
    
    def borrar_imc(self):
        self.cPeso.setText("")
        self.cAltura.setText("")
        self.cResultado.setText("")
    
    def calcular_porcentaje(self):
        numero = float(self.cNumero.text())
        porcentaje = float(self.cPorc.text())
        porc = (numero * porcentaje) / 100
        self.cResultadoP.setText(str(porc))
      
    def borrar_porcentaje(self):
        self.cNumero.setText("")
        self.cPorc.setText("")
        self.cResultadoP.setText("")


    


    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
     # Botones
    ui.bttnCalculadora.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.calculadora))
    ui.bttnImc.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.calc_imc))
    ui.bttnPorcentaje.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.calc_porc))
    ui.menubttn.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.menu))
    ui.menubttn_2.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.menu))
    ui.menubttn_3.clicked.connect(lambda: ui.stackedWidget.setCurrentWidget(ui.menu))
    sys.exit(app.exec_())
